
# specify custom environment variables
environment:
  matrix:
    - VisualStudioVersion: 14.0
      platform: x64
      configuration: Release
      vcvarsall_platform: "x64"
  global:
    MSVC_DEFAULT_OPTIONS: ON
    BOOST_ROOT: C:\Libraries\boost_1_60_0
    BOOST_LIBRARYDIR: C:\Libraries\boost_1_60_0\lib64-msvc-14.0
    PYTHON_LIBRARY: C:\Python27-x64\libs\python27.lib
    PYTHON_INCLUDE_DIR: C:\Python27-x64\include
    WXWIN: C:\wxWidgets-3.1.0\
    wxWidgets_ROOT_DIR: C:\wxWidgets-3.1.0\
    wxWidgets_INCLUDE_DIRS: C:\wxWidgets-3.1.0\include
    wxWidgets_LIBRARIES: C:\wxWidgets-3.1.0\lib\vc140_x64_dll
    SWIG_DIR: C:\Libraries\swigwin-3.0.11
    SWIG_EXECUTABLE: C:\Libraries\swigwin-3.0.11\swig.exe
    PYTHON_EXECUTABLE: C:\Python27-x64\python.exe
    CTEST_OUTPUT_ON_FAILURE: 1

# branches to build
branches:
  # whitelist
  only:
    - master

# Operating system (build VM template)
os: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input


# clone directory
clone_folder: c:\projects\isimpa

platform: x64
configuration: Release


# scripts to run before build
before_build:
  - ps: git rev-parse HEAD
  # msbuild will use x64 visual studio compiler
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
  # Copy x64 dll from system32 to python27 x64
  - cmd: copy c:\windows\system32\PYTHON27.DLL C:\Python27-x64\python27.dll
  # sent environment variables for wxWidgets
  - set WXWIN=C:\wxWidgets-3.1.0\
  - set wxWidgets_ROOT_DIR=%WXWIN%
  - set wxWidgets_LIB_DIR=%WXWIN%\lib\vc_dll
  - echo Download wxWidgets lib
  - ps: Start-FileDownload 'https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.0/wxWidgets-3.1.0.7z'
  - ps: Start-FileDownload 'https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.0/wxMSW-3.1.0_vc140_x64_Dev.7z'
  - cmd: 7z x wxWidgets-3.1.0.7z -oC:\wxWidgets-3.1.0
  - cmd: 7z x wxMSW-3.1.0_vc140_x64_Dev.7z -oC:\wxWidgets-3.1.0
  - cmd: dir %wxWidgets_LIBRARIES%
  # Download Release wxWidgets DLL's
  - ps: Start-FileDownload 'https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.0/wxMSW-3.1.0_vc140_x64_ReleaseDLL.7z' -Timeout 15000
  - cmd: 7z x wxMSW-3.1.0_vc140_x64_ReleaseDLL.7z -oC:\wxWidgets-3.1.0
  # install dependencies:
  - choco install poedit nsis 7zip.install
  - ps: Start-FileDownload 'https://github.com/nicolas-f/build_resources/raw/master/swigwin-3.0.11.zip' -FileName 'c:\Libraries\swigwin-3.0.11.zip' -Timeout 15000
  - ps: 7z x c:\Libraries\swigwin-3.0.11.zip -oC:\Libraries -r -y
  - cmd: SET PATH=%PATH%;%WXWIN%;%SWIG_DIR%;%wxWidgets_LIB_DIR%;C:\Program Files (x86)\Poedit\Gettexttools\bin;%BOOST_LIBRARYDIR%;
  - ps: swig.exe -version
  - echo Running cmake...
  - cmd: mkdir c:\projects\isimpa\build
  - cmd: cd c:\projects\isimpa\build
  - cmd: echo wxWidgets_CONFIGURATION:STRING=mswu > CMakeCache.txt
  - cmd: echo wxWidgets_LIB_DIR:PATH=%wxWidgets_LIBRARIES% >> CMakeCache.txt
  - cmd: echo wxWidgets_ROOT_DIR:PATH=%wxWidgets_ROOT_DIR% >> CMakeCache.txt
  - cmd: echo WX_LIB_DIR:INTERNAL=%wxWidgets_LIBRARIES% >> CMakeCache.txt
  - cmd: echo WX_ROOT_DIR:INTERNAL=%wxWidgets_ROOT_DIR% >> CMakeCache.txt
  - cmd: echo PYTHON_EXECUTABLE:FILEPATH=%PYTHON_EXECUTABLE% >> CMakeCache.txt
  - cmake --debug-output -G "Visual Studio 14 2015 Win64" c:\projects\isimpa

build_script:
  - cd c:\projects\isimpa\build
  - ECHO Building %configuration% %platform% with MSVC %VisualStudioVersion% using %PlatformToolset% PlatformToolset
  - dir
  - 'CALL "C:\Program Files (x86)\Microsoft Visual Studio %VisualStudioVersion%\VC\vcvarsall.bat" %vcvarsall_platform%'
  - msbuild "INSTALL.vcxproj" /consoleloggerparameters:Verbosity=minimal /target:Build  /p:Configuration=%configuration% /p:Platform=%platform% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
  - cd c:\projects\isimpa\build
  - 'CALL "C:\Program Files (x86)\Microsoft Visual Studio %VisualStudioVersion%\VC\vcvarsall.bat" %vcvarsall_platform%'
  - ECHO Package I-SIMPA %configuration% %platform% with MSVC %VisualStudioVersion% using %PlatformToolset% PlatformToolset
  - msbuild "PACKAGE.vcxproj" /consoleloggerparameters:Verbosity=minimal /target:Build  /p:Configuration=%configuration% /p:Platform=%platform% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

# Test script disabled, don't know why python can't find libsimpa under Appveyor
test_script:
  - choco install dependencywalker -y --allow-empty-checksums
  - depends.exe /f:1 /c /oc:c:\projects\isimpa\build\depends.txt c:\projects\isimpa\build\bin\isimpa.exe
  - cd c:\projects\isimpa\build
  - 'CALL "C:\Program Files (x86)\Microsoft Visual Studio %VisualStudioVersion%\VC\vcvarsall.bat" %vcvarsall_platform%'
  - ECHO Test I-SIMPA %configuration% %platform% with MSVC %VisualStudioVersion% using %PlatformToolset% PlatformToolset
  - msbuild "RUN_TESTS.vcxproj" /target:Build  /p:Configuration=%configuration% /p:Platform=%platform% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

on_finish:
    - if exist c:\projects\isimpa\build\depends.txt ( type c:\projects\isimpa\build\depends.txt )
    - if exist c:\projects\isimpa\build\Testing\Temporary\LastTest.log ( type c:\projects\isimpa\build\Testing\Temporary\LastTest.log )
artifacts:
  - path: 'build\*.exe'
    name: isimpa-win64-install
  - path: 'build\*.zip'
    name: isimpa-win64-standalone
  - path: 'build\CMakeFiles\CMakeOutput.log'
    name: cmake_output_log
  - path: 'build\CMakeFiles\CMakeError.log'
    name: cmake_output_log
